name: Publish production image
run-name: Publish production image
on:
  push:
    branches: main

jobs:
  build-and-deploy:
    name: Build and deploy
    uses: ./.github/workflows/_deploy_to_docker.yml
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
